services:
    iris:
        build:
            context: ./  # 这里把当前路径的上一级加到上下文环境中
            dockerfile: ./image-iris/Dockerfile  #指定dockerfile
        environment:
            IRIS_USERNAME: superuser
            IRIS_PASSWORD: SYS
        hostname: 2024demo
        container_name: fhirvalidation
        ports:
            - 1980:1972 
            - 52880:52773
        command: --check-caps false --ISCAgent false --log /usr/irissys/mgr/messages.log
        

